import { Location } from '../models';

export const mockLocations: Location[] = [
  {
    id: 1,
    name: "Cabane des Clos de Dessus",
    coord: { long: 1.167, lat: 42.71867 },
    altitude: 2023,
    places: 0,
    description: "[b]Depuis 2020, cette cabane est réservée au berger en été, et fermée le reste de l'année. Elle ne peut plus servir d'abri aux randonneurs.[/b] Notez la présence d'un abri très sommaire au fond du Clos contre un gros rocher pouvant abriter deux personnes en cas d'urgence. Itinéraire d'accès compliqué et principalement hors sentier (malgré ce que la carte mentionne), et très exposé aux avalanches. Soyez très prudent, tout particulièrement en cas de présence de neige. Depuis le parking de Peyrots (980m) au Sud de Salau, prendre la piste au Sud pendant 30min. Au deuxième lacet, après avoir laissé la cascade de Léziou sur la gauche, prendre un petit sentier sur la gauche (1100m). Progresser dans une forêt où on laisse une grange fermée à clé à 1173m sur la droite et suivre la sente dans la forêt. 1430m, main courante qui permet de traverser un couloir à avalanche encore dans la forêt, passage délicat. Penser à prendre du bois en sortant de la forêt. 1570m, passage câblé pour passer un ravin vertigineux, rester habile. Névé persistant (1820m) qu'il ne faut pas hésiter à contourner par le bas. Le sentier se dirige enfin vers les deux cascades que nous voyons depuis un moment, et vous amène sur le Clos (creux) juste au dessus où se trouve la cabane. Occupée par un berger en période destive, fermée sinon.",
    links: ["https://www.refuges.info/point/5554/cabane-non-gardee/cabane-des-Clos-de-Dessus/"],
    type: "Fermée",
    modified_at: "2024-01-24",
    region: null,
    departement: null,
    condition: "pobre"
  },
  {
    id: 2,
    name: "Cabane basse d'Ihizelai",
    coord: { long: -1.62638, lat: 43.32671 },
    altitude: 331,
    places: 0,
    description: "[b]À pied[/b] Depuis le parking de la Carrière d'Ascain, suivre la grosse piste qui monte vers la Rhune. la cabane est au bord du chemin.",
    links: ["https://www.refuges.info/point/4834/cabane-non-gardee/cabane-basse-d-Ihizelai/"],
    type: "cabane ouverte",
    modified_at: "2015-09-12",
    region: null,
    departement: null,
    condition: "normal"
  },
  {
    id: 3,
    name: "Bergerie Prat Baillat",
    coord: { long: 2.09795, lat: 42.67272 },
    altitude: 1700,
    places: 0,
    description: "Occupée l'été par un berger (Breton !), son chien et son chat et qui élève des chevaux IGN signale qu'elle est accessible en dehors de la période d'estive Un tuyau d'eau sur un des murs de la bergerie, marqué non potable (à traiter) Bois a profusion Depuis Quérigut, prendre la direction Montlouis A 4km, à un pseudo col à 1471m, prendre la route forestière à droite sur 3km La bergerie se trouve à main gauche à un coude de la piste",
    links: ["https://www.refuges.info/point/3489/cabane-non-gardee/bergerie-Prat-Baillat/"],
    type: "cabane ouverte",
    modified_at: "2013-08-06",
    region: null,
    departement: null,
    condition: "bé"
  },
  {
    id: 4,
    name: "Refuge de La Fruitiére",
    coord: { long: -0.09827613830566408, lat: 42.853330012446825 },
    altitude: 1371,
    places: 0,
    description: "Directement sur le parking de la Fruitière Hôtellerie de la fruitière.",
    links: [
      "http://www.pyrenees-refuges.com/fr/affiche.php?numenr=148",
      "https://www.refuges.info/point/6414/cabane-non-gardee/cabane-de-la-Fruitiere/"
    ],
    type: "cabane ouverte",
    modified_at: "2018-08-26",
    region: "Cauterets",
    departement: "Haute-Pyrénées",
    condition: "bé"
  },
  {
    id: 5,
    name: "Cabane du col de Couradabat",
    coord: { long: 0.30630802094488, lat: 43.007577531605 },
    altitude: 1030,
    places: 0,
    description: "Petite cabane sans bat-flanc, meublée d'1 canapé, 1 table et de chaises. https://www.visorando.com/images/inter/m-cabane-en-bon-etat-et-fonctionnelle-visorando-34317.jpg Les chiens sont interdits. Au col de Couradabat, sur le GRP Tour des baronnies de Bigorre. ?",
    links: [
      "https://www.refuges.info/point/6175/cabane-non-gardee/cabane-de-Couradabat/",
      "http://www.pyrenees-refuges.com/fr/affiche.php?numenr=1059"
    ],
    type: "cabane ouverte",
    modified_at: "2019-01-23",
    region: "Esparros",
    departement: "Haute-Pyrénées",
    condition: "normal"
  },
  {
    id: 6,
    name: "Cabane de la Jaça de Los cabres",
    coord: { long: 2.05065, lat: 42.54005 },
    altitude: 1740,
    places: 0,
    description: "Très sale. Ouverte à tous les vents. Impossible d'y dormir. Une grande cheminée.",
    links: ["https://www.refuges.info/point/4421/cabane-non-gardee/cabane-de-la-Jaca-de-Los-cabres/"],
    type: "cabane ouverte",
    modified_at: "2014-07-29",
    region: null,
    departement: null,
    condition: "pobre"
  },
  {
    id: 7,
    name: "Cabane de Lameza",
    coord: { long: 1.1202778, lat: 42.830278 },
    altitude: 1330,
    places: 0,
    description: "Cabane située à l'orée de la Forêt de Lamech, coté Ouest, au bord du GR10D, proche de la [->6263] un peu au Sud-Ouest en poursuivant ce même GR.",
    links: [
      "http://www.pyrenees-refuges.com/fr/affiche.php?numenr=1075",
      "https://www.refuges.info/point/7259/cabane-non-gardee/cabane-forestiere-de-Lameza/"
    ],
    type: "cabane ouverte",
    modified_at: "2020-10-08",
    region: "Seix",
    departement: "Ariège",
    condition: "normal"
  },
  {
    id: 8,
    name: "Abri pastoral de Pouilh",
    coord: { long: 1.1515107, lat: 42.7436254 },
    altitude: 1550,
    places: 0,
    description: "L'ancienne cabane (avec partie berger et randonneur) avait été détruite durant l'hiver 2013. La cabane a été reconstruite pour \"Jean le berger\" et les éleveurs de la vallée. Travaux de la cabane financés par L'Europe, l'Etat et la commune d'Oust.",
    links: ["https://www.refuges.info/point/5623/cabane-non-gardee/abri-pastoral-de-Pouilh/"],
    type: "Fermée",
    modified_at: "2024-12-19",
    region: null,
    departement: null,
    condition: "normal"
  },
  {
    id: 9,
    name: "Cabane d'Arrieu Tort",
    coord: { long: 0.442222, lat: 42.872222 },
    altitude: 1630,
    places: 0,
    description: "situee sur le chemin du lac balise en jaune et dont l autre extremite est accessible depuis la piste forestiere de risdifficile a trouver le chemin est tres peu visible cabane fermee pour l instant par l onf car trop endommagee",
    links: ["http://www.pyrenees-refuges.com/fr/affiche.php?numenr=28"],
    type: "cabane fermee",
    modified_at: null,
    region: "Bordères-Louron",
    departement: "Haute-Pyrénées",
    condition: "pobre"
  },
  {
    id: 10,
    name: "Cabane du Sagasti",
    coord: { long: -1.6758, lat: 43.2995 },
    altitude: 291,
    places: 0,
    description: "- grande cabane en bois (40 m2), entretenue et en bon état en juillet 2020 - fenêtres vitrées, volets et porte qui ferment bien - deux grandes tables avec bancs - vaisselle et évier - fontaine aménagée à côté de la cabane - esplanade herbeuse avec tables en bois fixes pour piqueniquer - cabane et esplanade entourées d'une clôture pour maintenir à distance le bétail, penser à bien refermer le portail L'accès y est interdit pendant les mois d'octobre et novembre où elle est réservée aux chasseurs.",
    links: ["https://www.refuges.info/point/7607/cabane-non-gardee/cabane-du-Sagasti/"],
    type: "cabane ouverte",
    modified_at: "2022-10-10",
    region: null,
    departement: null,
    condition: "bé"
  },
  {
    id: 11,
    name: "Cabane de Salontere (Neuve)",
    coord: { long: 0.7838888, lat: 42.842778 },
    altitude: 1450,
    places: 0,
    description: "tres belle cabane construite recemment chenil attenant pour acces il faut demander la clef a la mairie de fos deconseillee en periode de chasse tel mairie de fos 0561794161",
    links: ["http://www.pyrenees-refuges.com/fr/affiche.php?numenr=767"],
    type: "cabane ouverte",
    modified_at: null,
    region: "Fos",
    departement: "Haute-Garonne",
    condition: "bé"
  },
  {
    id: 12,
    name: "Cabane Peyrahitte",
    coord: { long: 0.05072593, lat: 42.8467405 },
    altitude: 1812,
    places: 0,
    description: "cabane spacieuse mais pas de couchage la porte d entree ne ferme pas un volet est abime",
    links: ["http://www.pyrenees-refuges.com/fr/affiche.php?numenr=464"],
    type: "cabane ouverte",
    modified_at: null,
    region: "Luz-Saint-Sauveur",
    departement: "Haute-Pyrénées",
    condition: "normal"
  },
  {
    id: 13,
    name: "Cabane du Planet",
    coord: { long: 0.6441666, lat: 42.872222 },
    altitude: 1600,
    places: 1,
    description: "reportee comme ruines sur les cartes mais a ete retape petite cabane posee sur la crete a l ouest du pic du burat propre et en bon etat eau de pluie uniquement a traiter",
    links: ["http://www.pyrenees-refuges.com/fr/affiche.php?numenr=1034"],
    type: "cabane ouverte",
    modified_at: null,
    region: "Burgalays",
    departement: "Haute-Garonne",
    condition: "bé"
  },
  {
    id: 14,
    name: "Refuge Salvador",
    coord: { long: 1.04933547, lat: 42.8569556 },
    altitude: 1500,
    places: 0,
    description: "vieille batisse de forme ogivale fermee porte scellee situee sous le pic du midi de bordes et au dessus d un abreuvoir la porte a une serrure hexagonale probablement ouverte avec une cle de 12 mais le refuge n a pas de lit seulement une cheminee et deux bancs rien de bien interessant si ce n est qu il montre la voie du pic du midi de bordes",
    links: ["http://www.pyrenees-refuges.com/fr/affiche.php?numenr=560"],
    type: "cabane fermee",
    modified_at: null,
    region: "Arrien-en-Bethmale",
    departement: "Ariège",
    condition: "pobre"
  }
];
